import type { Metadata } from "next";
import { Mitr } from "next/font/google";
import "./globals.css";
import AppShell from "@/components/layout/app-shell";

const mitr = Mitr({
  variable: "--font-mitr",
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["thai", "latin"],
});

export const metadata: Metadata = {
  title: "LogRag Project",
  description: "Generated by EXP Team-2",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th"
      className={`${mitr.variable} h-full antialiased font-sans`}
    >
      <body className="min-h-full flex flex-col font-sans bg-white text-slate-800">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
